name: itt632_nashcafe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_charts: ^0.5.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  flutter_stripe: ^10.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/logo.jpeg
    - assets/background.jpeg
    - assets/bowl_image.jpeg
    - assets/logo_nash.jpeg
    - assets/background2.jpeg
    - assets/chocalate_cake.jpeg
    - assets/french_fries.jpeg
    - assets/grilledsalmon.jpeg
    - assets/latte.jpg
    - assets/mashed_potatoes.jpeg
    - assets/nachos.jpeg
    - assets/sprite.jpeg
    - assets/steak.jpeg
    - assets/tiramisu_cake.jpeg
    - assets/spring_rolls.jpeg
    - assets/tea.jpg
    - assets/steamed_vegetables.jpg
    - assets/ice_cream_chocalate.jpeg
    - assets/coleslaw.jpeg
    - assets/prawn.jpeg
    - assets/mango_smoothie.jpeg
    - assets/mozarella_sticks.jpeg
    - assets/.env

  uses-material-design: true
